In [7]:
import pandas as pd

In [20]:


url = "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv"

df = pd.read_csv(url, nrows=100)
df.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LocationID    100 non-null    int64
 1   Borough       100 non-null    object
 2   Zone          100 non-null    object
 3   service_zone  100 non-null    object
dtypes: int64(1), object(3)
memory usage: 3.3+ KB

In [25]:
!uv add sqlalchemy psycopg2-binary

Resolved 120 packages in 0.64ms
Audited 12 packages in 0.22ms

In [29]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [60]:
print(pd.io.sql.get_schema(df, name='zones', con=engine))

CREATE TABLE zones (
	"LocationID" BIGINT,
	"Borough" TEXT,
	"Zone" TEXT,
	service_zone TEXT
)

In [61]:
df.head(0).to_sql(name='zones', con=engine, if_exists='replace')

0

In [35]:
df.head(0)

Empty DataFrame
Columns: [LocationID, Borough, Zone, service_zone]
Index: []

In [37]:
df.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [46]:
df.dtypes

LocationID       int64
Borough         object
Zone            object
service_zone    object
dtype: object

In [47]:
len(df)

100

In [62]:
df_iter = pd.read_csv(
    url,
    iterator=True,
)

In [53]:
!uv add tqdm

Resolved 120 packages in 0.83ms
Audited 12 packages in 0.41ms

In [54]:
from tqdm.auto import tqdm

In [58]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='zones', con=engine, if_exists='append')

0it [00:00, ?it/s]

In [59]:
df.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [63]:
first = True

for df_chunk in df_iter:

    if first:
        # Create table schema (no data)
        df_chunk.head(0).to_sql(
            name="zones",
            con=engine,
            if_exists="replace"
        )
        first = False
        print("Table created")

    # Insert chunk
    df_chunk.to_sql(
        name="zones",
        con=engine,
        if_exists="append"
    )

    print("Inserted:", len(df_chunk))

Table created
Inserted: 265